parameters:
    pim_webservice.handler.rest.product.class: CustomBundles\ApiBundle\Handler\Rest\ProductHandler

services:
    pim_webservice.handler.rest.product:
        class: %pim_webservice.handler.rest.product.class%
        arguments:
            - '@pim_webservice.serializer'
